### ISSUE TITLE
Error starting Ripple Wallet

### ISSUE THREAD

**Issue by rscheers** [LedgerHQ/ledger-wallet-ripple#17]
Starting the ripple app shows the following error and quits:
 Failed to load extension from C:\Program Files (x86)\Ledger Wallet Ripple. 
Default locale is defined but default data couldn't be loaded.
![error](https://user-images.githubusercontent.com/17256953/34082775-d632e40e-e364-11e7-9fda-b09aeb9a5c06.JPG)
More info:
Windows 10 with the x64 package.

**Comment by amougel** [comment]
The ledger wallet ripple is not intended to be used with Chrome Browser and maybe you tried to open it using Chrome.

If you indeed tried to open it with chrome, here is how you should open it:
- double click the shortcut on your desktop or start menu.
- if nothing happens, please download and install [this version](https://github.com/LedgerHQ/ledger-wallet-ripple/releases/download/1.0.2/setup_ledger_wallet_ripple_win_x86.exe) while we fix the issue.

If not, can you describe the steps you followed to get this error?

**Comment by rscheers** [comment]
Hi,

I have installed that x86 version also.
I have let setup create a shortcut and I start the app with this shortcut.
It takes a little time and then the error message appears.

I do not start it from Chrome, nor do I have Chrome running.

**Comment by amougel** [comment]
Thanks for the feedback. While we work on a fix, please follow the [readme](https://github.com/LedgerHQ/ledger-wallet-ripple/blob/master/README.md) to manage XRP on your wallet.

**Comment by rscheers** [comment]
Tried that also 😊
But got build errors:

[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * org.scala-js:sbt-scalajs:0.6.5 -> 0.6.15
[warn] Run 'evicted' to see detailed eviction warnings
[warn] There may be incompatibilities among your library dependencies.
[warn] Here are some of the libraries that were evicted:
[warn]  * org.scala-js:scalajs-dom_sjs0.6_2.11:0.8.0 -> 0.9.0
[warn] Run 'evicted' to see detailed eviction warnings
[warn] C:\Users\Remko\ledger-wallet-ripple\src\main\scala\co\ledger\wallet\core\                                                                                                                                                                                               utils\logs\Logger.scala:170: @JSName on top-level native JS classes and objects                                                                                                                                                                                                (or native JS classes and objects inside Scala objects) is deprecated, and shoul                                                                                                                                                                                               d be replaced by @JSGlobal (with the same meaning). This will be enforced in 1.0                                                                                                                                                                                               .
[warn]   (you can suppress this warning in 0.6.x by passing the option `-P:scala                                                                                                                                                                                               js:suppressMissingJSGlobalDeprecations` to scalac)
[warn]   @JSName("sourceMap.SourceMapConsumer")
[warn]    ^
[warn] C:\Users\Remko\ledger-wallet-ripple\src\main\scala\co\ledger\wallet\web\r                                                                                                                                                                                               ipple\components\Spinner.scala:193: @JSName on top-level native JS classes and o                                                                                                                                                                                               bjects (or native JS classes and objects inside Scala objects) is deprecated, an                                                                                                                                                                                               d should be replaced by @JSGlobal (with the same meaning). This will be enforced                                                                                                                                                                                                in 1.0.
[warn]   (you can suppress this warning in 0.6.x by passing the option `-P:scala                                                                                                                                                                                               js:suppressMissingJSGlobalDeprecations` to scalac)
[warn]   @JSName("SpinnerScope")
[warn]    ^
[warn] C:\Users\Remko\ledger-wallet-ripple\src\main\scala\co\ledger\wallet\web\r                                                                                                                                                                                               ipple\debug\LedgerDebugInterface.scala:36: @JSExport on objects is deprecated an                                                                                                                                                                                               d will be removed in 1.0.0. Use @JSExportTopLevel instead. Note that it exports                                                                                                                                                                                                the object itself (rather than a 0-arg function returning the object), so the ca                                                                                                                                                                                               lling JavaScript code must be adapted.
[warn]   (you can suppress this warning in 0.6.x by passing the option `-P:scala                                                                                                                                                                                               js:suppressExportDeprecations` to scalac)
[warn] @JSExport("LedgerDebugInterface")
[warn]  ^
[warn] C:\Users\Remko\ledger-wallet-ripple\src\main\scala\co\ledger\wallet\web\r                                                                                                                                                                                               ipple\wallet\RippleLibApi.scala:411: match may not be exhaustive.
[warn] It would fail on the following inputs: APIOption(_, _, _, _, _), Disconne                                                                                                                                                                                               ctArgument(_), GetTransactionParam(_, _), GetTransactionsParam(_, _), PaymentPar                                                                                                                                                                                               am(_, _, _), SignParam(_, _, _), SubmitParam(_)
[warn]         obj match {
[warn]         ^
[warn] there were 24 deprecation warnings; re-run with -deprecation for details
[warn] there were three feature warnings; re-run with -feature for details
[warn] 6 warnings found

**Comment by amougel** [comment]
These are not errors but warnings. Have you tried running the app with nwjs after the build? Looking at your logs, the apps should work fine.

**Comment by rscheers** [comment]
Sorry, I did not copy everything.
This is where the error happens:
org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$OptimizeException: The Scala.js optimizer crashed while optimizing jl_Character$.charTypes$lzycompute__p1__AB: java.lang.StackOverflowError
Methods attempted to inline:

        at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore.optimize(OptimizerCore.scala:154)
        at org.scalajs.core.tools.linker.frontend.optimizer.GenIncOptimizer$MethodImpl.process(GenIncOptimizer.scala:935)
        at org.scalajs.core.tools.linker.frontend.optimizer.ParIncOptimizer$$anonfun$processAllTaggedMethods$2.apply(ParIncOptimizer.scala:87)
        at org.scalajs.core.tools.linker.frontend.optimizer.ParIncOptimizer$$anonfun$processAllTaggedMethods$2.apply(ParIncOptimizer.scala:86)
        at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach_quick(ParArray.scala:145)
        at scala.collection.parallel.mutable.ParArray$ParArrayIterator.foreach(ParArray.scala:138)
        at scala.collection.parallel.ParIterableLike$Foreach.leaf(ParIterableLike.scala:975)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply$mcV$sp(Tasks.scala:54)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
        at scala.collection.parallel.Task$$anonfun$tryLeaf$1.apply(Tasks.scala:53)
        at scala.collection.parallel.Task$class.tryLeaf(Tasks.scala:56)
        at scala.collection.parallel.ParIterableLike$Foreach.tryLeaf(ParIterableLike.scala:972)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.internal(Tasks.scala:172)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.internal(Tasks.scala:514)
        at scala.collection.parallel.AdaptiveWorkStealingTasks$WrappedTask$class.compute(Tasks.scala:162)
        at scala.collection.parallel.AdaptiveWorkStealingForkJoinTasks$WrappedTask.compute(Tasks.scala:514)
        at scala.concurrent.forkjoin.RecursiveAction.exec(RecursiveAction.java:160)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.StackOverflowError
        at scala.collection.AbstractIterable.<init>(Iterable.scala:54)
        at scala.collection.AbstractSeq.<init>(Seq.scala:40)
        at scala.collection.immutable.List.<init>(List.scala:84)
        at scala.collection.immutable.$colon$colon.<init>(List.scala:356)
        at scala.collection.immutable.List.$colon$colon(List.scala:111)
at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformExprs$1$$anonfun$apply$11.apply(OptimizerCore.scala:748)
        at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformExprs$1$$anonfun$apply$11.apply(OptimizerCore.scala:747)
        at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformExprs$1$$anonfun$apply$11.apply(OptimizerCore.scala:748)
        at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformExprs$1$$anonfun$apply$11.apply(OptimizerCore.scala:747)
        at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformExprs$1$$anonfun$apply$11.apply(OptimizerCore.scala:748)
        at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformExprs$1$$anonfun$apply$11.apply(OptimizerCore.scala:747)
        at org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$$anonfun$org$scalajs$core$tools$linker$frontend$optimizer$OptimizerCore$$pretransformExprs$1$$anonfun$apply$11.apply(OptimizerCore.scala:748)
[error] (compile:fastOptJS) org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$OptimizeException: The Scala.js optimizer crashed while optimizing jl_Character$.charTypes$lzycompute__p1__AB: java.lang.StackOverflowError
[error] Methods attempted to inline:
[error] Total time: 28 s, completed Dec 17, 2017 11:24:32 PM
[error] Not a valid command: Xss4m
[error] Not a valid key: Xss4m (similar: less)
[error] Xss4m
[error]      ^

And no chrome-app folder is created…

**Comment by amougel** [comment]
Follow these steps: 
- Open control panel
- Go to: System and Security -> System -> Advanced system settings (on th left) -> environment variables
- Under " System variables" click on "New"
- Name: JAVA_OPTS  and Value: -Xms512m -Xmx1024m
- Confirm and apply
- Close and reopen your console and build.

**Comment by rscheers** [comment]
Tried it, and added JAVA_TOOL_OPTIONS  because I have Oracle Java,  but still an error:

[error] (compile:fastOptJS) org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$OptimizeException: The Scala.js optimizer crashed while optimizing jl_Character$.charTypes$lzycompute__p1__AB: java.lang.StackOverflowError
[error] Methods attempted to inline:
[error] Total time: 30 s, completed Dec 17, 2017 11:48:13 PM
[error] Not a valid command: Xss4m
[error] Not a valid key: Xss4m (similar: less)
[error] Xss4m
[error]      ^
Picked up JAVA_TOOL_OPTIONS: -Xms512m -Xmx1024m

**Comment by rscheers** [comment]
I think I’ll wait for an updated ripple wallet app. 😊

From: Remko Scheers
Sent: Sunday, December 17, 2017 11:54 PM
To: 'LedgerHQ/ledger-wallet-ripple' <reply@reply.github.com>; LedgerHQ/ledger-wallet-ripple <ledger-wallet-ripple@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [LedgerHQ/ledger-wallet-ripple] Error starting Ripple Wallet (#17)

Tried it, and added JAVA_TOOL_OPTIONS  because I have Oracle Java,  but still an error:

[error] (compile:fastOptJS) org.scalajs.core.tools.linker.frontend.optimizer.OptimizerCore$OptimizeException: The Scala.js optimizer crashed while optimizing jl_Character$.charTypes$lzycompute__p1__AB: java.lang.StackOverflowError
[error] Methods attempted to inline:
[error] Total time: 30 s, completed Dec 17, 2017 11:48:13 PM
[error] Not a valid command: Xss4m
[error] Not a valid key: Xss4m (similar: less)
[error] Xss4m
[error]      ^
Picked up JAVA_TOOL_OPTIONS: -Xms512m -Xmx1024m

**Comment by amougel** [comment]
Which version of the JSDK do you have installed?

**Comment by rscheers** [comment]
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) Client VM (build 25.151-b12, mixed mode)

**Comment by amougel** [comment]
The new release is available so I'm closing this thread

**Comment by cryptokingzz** [comment]
i have the same issue

**Comment by cryptokingzz** [comment]
was this ever resolved
