### ISSUE TITLE
can't start app with nw: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by brenzi** [LedgerHQ/ledger-wallet-ripple#35]
I've built the wallet as the binary deb didn't work on my ubuntu16.04 (couldn't resolve libnss3.so)

I've installed nw.js
```
npm i -g nwjs
```
and then try to (in `ledger-wallet-ripple/target/chrome-app`)
```
> nw .
TypeError: Cannot read property 'split' of undefined
    at module.exports (/home/brenzi/.nvm/versions/node/v6.9.2/lib/node_modules/nwjs/lib/old-version.js:2:19)
    at module.exports (/home/brenzi/.nvm/versions/node/v6.9.2/lib/node_modules/nwjs/lib/get-path.js:10:26)
    at Command.module.exports (/home/brenzi/.nvm/versions/node/v6.9.2/lib/node_modules/nwjs/lib/run.js:16:16)
    at Command.listener (/home/brenzi/.nvm/versions/node/v6.9.2/lib/node_modules/nwjs/node_modules/commander/index.js:315:8)
    at emitOne (events.js:96:13)
    at Command.emit (events.js:188:7)
    at Command.parseArgs (/home/brenzi/.nvm/versions/node/v6.9.2/lib/node_modules/nwjs/node_modules/commander/index.js:655:12)
    at Command.parse (/home/brenzi/.nvm/versions/node/v6.9.2/lib/node_modules/nwjs/node_modules/commander/index.js:475:21)
    at Object.<anonymous> (/home/brenzi/.nvm/versions/node/v6.9.2/lib/node_modules/nwjs/nw:64:18)
    at Module._compile (module.js:570:32)

```

**Comment by amougel** [comment]
You need to download nwjs from their website. I don't think the npm package works. You still can download the zipped version, which is already built for linux.

**Comment by brenzi** [comment]
The zipped version shows the same issue, will try nwjs from their website

**Comment by brenzi** [comment]
downloaded nw.js from their website. Works.

thanks
